name: Schedule Netlify Build
on:
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    name: Call the Netlify Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_URL }}
